[project]
name = "labs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.4.2",
]
[tool.coverage.run]
# Исключаем файлы
omit = [
    "src/main.py",
    "src/cli.py",
    "tests/*",
    "*/__init__.py",
    "*/constants.py",
    "src/async_sheduler.py"
]
